In [1]:
using Pkg
Pkg.activate("..")
using Revise
includet("gradients.jl")
includet("matrices.jl")
using LinearAlgebra

  Activating project at `~/Workspace/CSC381`


In [2]:
using TypedPolynomials

In [3]:
d=4
z = ntuple(i -> Variable{Symbol("x", i)}(), d)

z[1] + z[2]

x1 + x2

In [4]:
p = 2x + 3.0x^2*y^2 - y*z^4

LoadError: UndefVarError: x not defined

In [5]:
p = 2x + 3.0x^2*y^2 - y*z^4

-yz⁴ + 3.0x²y² + 2.0x

In [6]:
differentiate(p, x)

6.0xy² + 2.0

In [7]:
variables(p)

(x, y, z)

In [8]:
p.terms

3-element Vector{Term{Float64, Monomial{(x, y, z), 3}}}:
 -yz⁴
 3.0x²y²
 2.0x

In [9]:
p.terms[1].coeffecient

LoadError: type Term has no field coeffecient

In [10]:
p.terms[1].coefficient

-1.0

In [11]:
p.terms[1].monomial

yz⁴

In [12]:
p.terms[1].monomial

yz⁴

In [13]:
p.terms[1].monomial.exponents

(0, 1, 4)

In [2]:
x = rand(5, 5)

┌ Error: Failed to revise /home/DAVIDSON/komateer/Workspace/CSC381/dl_f22_project-0-KostasMateerStudent/matrices.jl
│   exception = (LoadError("/home/DAVIDSON/komateer/Workspace/CSC381/dl_f22_project-0-KostasMateerStudent/matrices.jl", 5, "line break in \":\" expression"), Union{Ptr{Nothing}, Base.InterpreterIP}[Ptr{Nothing} @0x0000152362b60230])
└ @ Revise /home/DAVIDSON/komateer/.julia/packages/Revise/VskYC/src/packagedef.jl:710
┌ Warning: The running code does not match the saved version for the following files:
│ 
│   /home/DAVIDSON/komateer/Workspace/CSC381/dl_f22_project-0-KostasMateerStudent/matrices.jl
│ 
│ If the error was due to evaluation order, it can sometimes be resolved by calling `Revise.retry()`.
│ Use Revise.errors() to report errors again. Only the first error in each file is shown.
│ Your prompt color may be yellow until the errors are resolved.
└ @ Revise /home/DAVIDSON/komateer/.julia/packages/Revise/VskYC/src/packagedef.jl:818


5×5 Matrix{Float64}:
 0.228636  0.573435  0.611485  0.995619  0.931872
 0.663651  0.150334  0.510023  0.851406  0.851764
 0.59894   0.615654  0.779372  0.894771  0.571519
 0.695809  0.808321  0.202628  0.17757   0.383017
 0.451322  0.861504  0.550817  0.248059  0.354303

In [3]:
x = ones(5, 5)

5×5 Matrix{Float64}:
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0

In [4]:
y = ones(5, 2)

5×2 Matrix{Float64}:
 1.0  1.0
 1.0  1.0
 1.0  1.0
 1.0  1.0
 1.0  1.0

In [6]:
A = [1 2 3; 4 1 6; 7 8 1]

3×3 Matrix{Int64}:
 1  2  3
 4  1  6
 7  8  1

In [7]:
B = A = [10 11 12; 1 1 6; 7 8 1]

3×3 Matrix{Int64}:
 10  11  12
  1   1   6
  7   8   1

In [8]:
A*B

3×3 Matrix{Int64}:
 195  217  198
  53   60   24
  85   93  133

In [11]:
for i in A
    print(i)
    print('\n')
end

10
1
7
11
1
8
12
6
1


In [14]:
size(A)

(3, 3)

In [15]:
x = size(A)

(3, 3)

In [16]:
x[2]

3

In [17]:
x = size(A)[2]

3

In [18]:
v = ones(2,2)

┌ Error: Failed to revise /home/DAVIDSON/komateer/Workspace/CSC381/dl_f22_project-0-KostasMateerStudent/matrices.jl
│   exception = (LoadError("/home/DAVIDSON/komateer/Workspace/CSC381/dl_f22_project-0-KostasMateerStudent/matrices.jl", 8, "line break in \":\" expression"), Union{Ptr{Nothing}, Base.InterpreterIP}[Ptr{Nothing} @0x0000152362b60230])
└ @ Revise /home/DAVIDSON/komateer/.julia/packages/Revise/VskYC/src/packagedef.jl:710


2×2 Matrix{Float64}:
 1.0  1.0
 1.0  1.0

In [20]:
size(v)[2]

2

In [21]:
v = ones(2)

┌ Error: Failed to revise /home/DAVIDSON/komateer/Workspace/CSC381/dl_f22_project-0-KostasMateerStudent/matrices.jl
│   exception = (LoadError("/home/DAVIDSON/komateer/Workspace/CSC381/dl_f22_project-0-KostasMateerStudent/matrices.jl", 6, "line break in \":\" expression"), Union{Ptr{Nothing}, Base.InterpreterIP}[Ptr{Nothing} @0x0000152362b60230])
└ @ Revise /home/DAVIDSON/komateer/.julia/packages/Revise/VskYC/src/packagedef.jl:710


2-element Vector{Float64}:
 1.0
 1.0

In [22]:
size(v)

(2,)

In [15]:
v1 = [1, 2, 3]
v2 = [5, 6, 7, 6]
#println(dot(v1, v2))
println(dot_product(v1, v2))

LoadError: AssertionError: size(vec1) == size(vec2)

In [41]:
size(v1)

(3,)

In [7]:
v1 = [1, 2, 3]

3-element Vector{Int64}:
 1
 2
 3

In [8]:
println(dot_product(v1, v2))

LoadError: AssertionError: size(vec1) == size(vec2)

In [16]:
ones(size(v1)[1])

3-element Vector{Float64}:
 1.0
 1.0
 1.0

In [24]:
matrix = [1 2 3; 4 5 6; 7 8 9]

3×3 Matrix{Int64}:
 1  2  3
 4  5  6
 7  8  9

In [37]:
matrix[4]

2

In [38]:
product_vector = Array{Float64}(undef, size(v1)[1], size(matrix)[2])

3×3 Matrix{Float64}:
 1.1566e-310   1.15664e-310    5.0e-324
 1.1566e-310   1.15665e-310  NaN
 1.15665e-310  1.15665e-310    1.14078e-310

In [46]:
for i in 1:size(matrix)[1]
    println(matrix[i, :])
end

[1, 2, 3]
[4, 5, 6]
[7, 8, 9]


In [26]:
v1 = [1, 2, 3]

3-element Vector{Int64}:
 1
 2
 3

In [14]:
println(dot_product(matrix[1, :], v1))

14


In [51]:
println(dot(matrix[1,:], v1))

14


In [27]:
print(multiply(matrix, v1))

[14.0, 32.0, 50.0]

In [ ]:
println(typeof(multiply(matrix, v1)))

In [30]:
mat1 = [1 2 3; 4 5 6; 7 8 9]
mat2 = [1 2 3; 4 5 6]

2×3 Matrix{Int64}:
 1  2  3
 4  5  6

In [31]:
multiply(mat1, mat2)

LoadError: AssertionError: (size(mat1))[2] == (size(mat2))[1]

In [4]:
length(mat1)

9

In [9]:
for i in 1:length(mat1)
    println(i)
end

1
2
3
4
5
6
7
8
9


In [18]:
a = ones(2, 2)

2×2 Matrix{Float64}:
 1.0  1.0
 1.0  1.0

In [20]:
a = cat(2, a, [2 2])

LoadError: UndefKeywordError: keyword argument dims not assigned

In [34]:
@polyvar x y z

(x, y, z)

In [35]:
p = 2x + 3.0x^2*y^2 - y*z^4

-yz⁴ + 3.0x²y² + 2.0x

In [36]:
p(x=>3, y=>-4, z=>.05)

438.000025

In [37]:
differentiate(p, x)

6.0xy² + 2.0

In [41]:
vector = [3, 4, 5]

3-element Vector{Int64}:
 3
 4
 5

In [49]:
norm(vector, 4)

5.569212227823757

In [50]:
p_norm(vector, 4)

5.569212227823757

In [43]:
4^1/5

0.8

In [44]:
4**2/5

LoadError: syntax: use "x^y" instead of "x**y" for exponentiation, and "x..." instead of "**x" for splatting.

In [45]:
4^(1/5)

1.3195079107728942

In [51]:
a = [1 2 3; 4 5 6; 7 8 9]
b = [1, 2, 3]

3-element Vector{Int64}:
 1
 2
 3

In [56]:
multiply(a, b)

3-element Vector{Float64}:
 14.0
 32.0
 50.0

In [57]:
multiply(a, b)

3-element Vector{Float64}:
 14.0
 32.0
 50.0

In [58]:
a = ones(100, 100)

100×100 Matrix{Float64}:
 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  …  1.0  1.0  1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0     1.0  1.0  1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0     1.0  1.0  1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0     1.0  1.0  1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0     1.0  1.0  1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  …  1.0  1.0  1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0     1.0  1.0  1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0     1.0  1.0  1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0     1.0  1.0  1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0     1.0  1.0  1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  …  1.0  1.0  1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0     1.0  1.0  1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0

In [60]:
b = ones(100)

100-element Vector{Float64}:
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 ⋮
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0

In [61]:
multiply(a, b)

100-element Vector{Float64}:
 100.0
 100.0
 100.0
 100.0
 100.0
 100.0
 100.0
 100.0
 100.0
 100.0
 100.0
 100.0
 100.0
   ⋮
 100.0
 100.0
 100.0
 100.0
 100.0
 100.0
 100.0
 100.0
 100.0
 100.0
 100.0
 100.0

In [64]:
Pkg.add("Distributions")
using Test
using Distributions
using LinearAlgebra

NUM_GOOD_TESTS = 20
NUM_BAD_TESTS = 10
MAX_DIM = 100

   Resolving package versions...
    Updating `~/Workspace/CSC381/Project.toml`
  [31c24e10] + Distributions v0.25.65
    Updating `~/Workspace/CSC381/Manifest.toml`
  [49dc2e85] + Calculus v0.5.1
  [9e997f8a] + ChangesOfVariables v0.1.4
  [9a962f9c] + DataAPI v1.10.0
  [b429d917] + DensityInterface v0.4.0
  [31c24e10] + Distributions v0.25.65
  [ffbed154] + DocStringExtensions v0.8.6
  [fa6b7ba4] + DualNumbers v0.6.8
  [1a297f60] + FillArrays v0.13.2
  [34004b35] + HypergeometricFunctions v0.3.11
  [3587e190] + InverseFunctions v0.1.7
  [92d709cd] + IrrationalConstants v0.1.1
  [692b3bcd] + JLLWrappers v1.4.1
  [2ab3a3ac] + LogExpFunctions v0.3.15
  [e1d29d7a] + Missings v1.0.2
  [77ba4419] + NaNMath v1.0.1
  [90014a1f] + PDMats v0.11.16
  [21216c6a] + Preferences v1.3.0
  [1fd47b50] + QuadGK v2.4.2
  [189a3867] + Reexport v1.2.2
  [79098fc4] + Rmath v0.7.0
  [a2af1166] + SortingAlgorithms v1.0.1
  [276daf66] + SpecialFunctions v2.1.7
  [82ae8749] + StatsAPI v1.4.0
  [2913bbd2] + Stat

100

In [65]:
@testset "vector_multiply" begin
    for i in 1:NUM_GOOD_TESTS
        rows = rand(1:MAX_DIM)
        cols = rand(1:MAX_DIM)
        v⃗ = rand(Uniform(-100,100), cols)
        𝕄 = rand(Uniform(-100,100), rows, cols)
        @test isapprox(multiply(𝕄, v⃗), 𝕄*v⃗)
    end
    for i in 1:NUM_BAD_TESTS÷2
        rows = rand(1:MAX_DIM)
        cols = rand(1:MAX_DIM)
        extra = rand(1:MAX_DIM)
        v⃗₁ = rand(Uniform(-100,100), cols)
        v⃗₂ = rand(Uniform(-100,100), cols+extra)
        𝕄₁ = rand(Uniform(-100,100), rows, cols)
        𝕄₂ = rand(Uniform(-100,100), rows, cols+extra)
        @test_throws Exception multiply(𝕄₁,v⃗₂)
        @test_throws Exception multiply(𝕄₂,v⃗₁)
    end
end



vector_multiply: Error During Test at In[65]:7
  Test threw exception
  Expression: isapprox(multiply(𝕄, v⃗), 𝕄 * v⃗)
  DimensionMismatch("dimensions must match: a has dims (Base.OneTo(59),), b has dims (Base.OneTo(100),), mismatch at 1")
  Stacktrace:
    [1] promote_shape
      @ ./indices.jl:178 [inlined]
    [2] promote_shape
      @ ./indices.jl:169 [inlined]
    [3] -(A::Vector{Float64}, B::Vector{Float64})
      @ Base ./arraymath.jl:38
    [4] isapprox(x::Vector{Float64}, y::Vector{Float64}; atol::Int64, rtol::Float64, nans::Bool, norm::typeof(norm))
      @ LinearAlgebra /opt/pub/eb/apps/all/Julia/1.7.0/share/julia/stdlib/v1.7/LinearAlgebra/src/generic.jl:1706
    [5] isapprox(x::Vector{Float64}, y::Vector{Float64})
      @ LinearAlgebra /opt/pub/eb/apps/all/Julia/1.7.0/share/julia/stdlib/v1.7/LinearAlgebra/src/generic.jl:1706
    [6] eval_test(evaluated::Expr, quoted::Expr, source::LineNumberNode, negate::Bool)
      @ Test /opt/pub/eb/apps/all/Julia/1.7.0/share/julia/stdlib/

LoadError: Some tests did not pass: 11 passed, 0 failed, 19 errored, 0 broken.

In [68]:
rows = rand(1:MAX_DIM)
cols = rand(1:MAX_DIM)
v⃗ = rand(Uniform(-100,100), cols)
𝕄 = rand(Uniform(-100,100), rows, cols)

85×27 Matrix{Float64}:
 -19.7859     56.2054   -86.1531    …   33.2099   -11.4163    44.441
  50.0199    -36.3382   -60.2536       -40.8576   -18.3342   -90.7855
  61.2939     99.6453    82.1099       -19.8378    98.0117   -30.7436
  -3.35841   -51.1963    42.2662        38.3052     7.40226   33.9567
 -97.6525     55.9706     4.16822      -52.5154   -20.919    -17.3273
 -70.6984     42.8991    34.8476    …  -37.4774     9.59924  -51.4295
 -49.5961    -59.2721   -17.4077       -47.6283   -13.6937    20.3427
 -15.362      12.4887    21.2271       -47.3818   -56.913     31.0712
  78.6541     -6.38683   39.4379       -50.2814    15.9564   -39.3425
  58.0734     -5.42559   11.713        -22.3655   -48.2146    27.623
 -79.7904    -87.0792   -65.7733    …  -65.6901   -75.5367   -50.9489
  25.5162     41.6506     9.32216      -79.512     77.1073   -76.2989
 -28.5014    -24.3658    44.9666       -77.2366    51.5938   -38.8351
   ⋮                                ⋱               ⋮        
 -17.83

In [73]:
v⃗

27-element Vector{Float64}:
  30.765753317166002
  18.65299134541884
  58.585619059773705
 -20.017503843096137
 -46.6299538154989
 -12.395166509778704
  27.048989241373846
  60.88810983827665
   6.914849701228505
  77.13145831492116
 -43.19343151394746
  55.82949393581288
 -27.303179279473014
   ⋮
  91.26834721614901
  11.543179453701441
 -80.32038644831601
 -53.62576276889725
 -96.78234040096585
 -83.22871059285521
 -24.33217679707367
 -33.882946843675384
  69.54476129327045
  80.25648591469451
 -96.4424778255015
  23.824554474556308

In [69]:
isapprox(multiply(𝕄, v⃗), 𝕄*v⃗)

LoadError: DimensionMismatch("dimensions must match: a has dims (Base.OneTo(27),), b has dims (Base.OneTo(85),), mismatch at 1")

In [71]:
multiply(𝕄, v⃗)

27-element Vector{Float64}:
 -15545.718874017646
 -12370.9253209653
  -9593.385793321304
  -6262.849406142683
  28990.41469734518
 -19548.06750187244
  23964.18925554551
 -21588.98931989649
  -5346.856413992011
  -1539.7993932221848
 -25293.052671912494
 -20440.944639087516
   8431.533829572978
      ⋮
 -11278.25660682862
  12965.940453512521
   1917.9498896819234
  28238.24971529218
  17771.464317012647
  -4387.725664785756
  26834.496106633233
 -13370.648262755654
 -13937.34651424951
   6540.611489945436
   1775.4433567224692
 -42634.63771763967

In [72]:
𝕄*v⃗

85-element Vector{Float64}:
 -15545.71887401765
 -12370.9253209653
  -9593.385793321304
  -6262.849406142684
  28990.414697345175
 -19548.067501872443
  23964.1892555455
 -21588.989319896493
  -5346.856413992008
  -1539.7993932221857
 -25293.052671912497
 -20440.94463908752
   8431.53382957298
      ⋮
   5290.430588724988
  19675.526301176236
   -748.3571980694107
  -4920.4144609651785
  -1030.7889881707554
 -23762.02302974539
   6007.23984435469
    996.114059362782
   4650.241686619151
 -15141.350063473308
 -26509.11761479971
   7736.69170675647

In [79]:
dim1 = rand(1:MAX_DIM)
dim2 = rand(1:MAX_DIM)
dim3 = rand(1:MAX_DIM)
𝕄₁ = rand(Uniform(-100,100), dim1, dim2)
𝕄₂ = rand(Uniform(-100,100), dim2, dim3)

33×26 Matrix{Float64}:
  -0.60607   -3.94645   -1.32449   …   39.9843    -45.004     57.2073
  16.1038   -74.7604    67.0655        38.1959     37.265    -65.5337
  68.9963    -7.10165  -54.4705       -40.2707     37.7529    28.4158
   1.2755   -54.9423    27.6009       -70.0936      1.13713   62.7485
   4.32557   55.5341    97.4063       -97.8428     36.7249    20.1369
 -65.9082   -23.056    -21.4531    …   99.8677    -80.2391    51.3468
 -65.6688    96.3783   -63.2055       -90.2015    -80.5028   -73.2885
  31.6885   -31.5698   -50.8671        -8.53331   -16.4505    53.3287
 -12.2743   -34.3329    -0.615106      44.7504     71.1285   -46.3226
 -94.6165   -53.7419   -18.8867       -59.5602    -58.2387    -2.19624
 -95.5421    72.0919   -76.087     …   10.5848     22.3355    73.5577
  42.1159    -1.18522   31.6472        65.2062     65.4407    27.4274
  41.7135    20.2805    43.0934        -5.28732   -36.4694    62.9155
   ⋮                               ⋱                           ⋮
 

In [83]:
𝕄₁

29×33 Matrix{Float64}:
  68.6574   -48.8602     54.2626   …  -76.8885    26.8986    73.9771
  37.3505   -87.8101     79.6288       30.5542   -55.3335    88.5516
  44.7883   -26.9071     37.5674       79.4874    99.9972   -82.0193
  31.2354   -72.228     -85.3833       65.4425    20.6795    41.2269
 -80.4092   -39.6994     56.073       -26.0234    55.8118     7.80553
  84.278     64.1453    -15.1399   …  -82.7819   -49.8367    55.9909
 -81.5143    65.098     -77.862       -93.01      71.2817   -43.0428
  14.359    -69.4769     14.4197       12.0781   -82.2091    68.411
 -42.024     21.1964     97.4651      -83.1674    -9.02469  -41.6943
 -75.4876    -0.346284    9.23417      52.7245    95.0699    87.9338
 -86.2884   -20.3702     19.3787   …   71.2632    12.5483     7.56904
 -22.64     -32.541     -80.4109       74.4036   -53.1443    -9.91012
  90.0966    69.276      77.2589       64.3323   -54.3436   -14.6246
   ⋮                               ⋱    ⋮                   
 -81.7791   -44.7

In [84]:
𝕄₂

33×26 Matrix{Float64}:
  -0.60607   -3.94645   -1.32449   …   39.9843    -45.004     57.2073
  16.1038   -74.7604    67.0655        38.1959     37.265    -65.5337
  68.9963    -7.10165  -54.4705       -40.2707     37.7529    28.4158
   1.2755   -54.9423    27.6009       -70.0936      1.13713   62.7485
   4.32557   55.5341    97.4063       -97.8428     36.7249    20.1369
 -65.9082   -23.056    -21.4531    …   99.8677    -80.2391    51.3468
 -65.6688    96.3783   -63.2055       -90.2015    -80.5028   -73.2885
  31.6885   -31.5698   -50.8671        -8.53331   -16.4505    53.3287
 -12.2743   -34.3329    -0.615106      44.7504     71.1285   -46.3226
 -94.6165   -53.7419   -18.8867       -59.5602    -58.2387    -2.19624
 -95.5421    72.0919   -76.087     …   10.5848     22.3355    73.5577
  42.1159    -1.18522   31.6472        65.2062     65.4407    27.4274
  41.7135    20.2805    43.0934        -5.28732   -36.4694    62.9155
   ⋮                               ⋱                           ⋮
 

In [88]:
multiply(𝕄₁, 𝕄₂)

29


29×26 Matrix{Float64}:
  -7217.73        761.369   -7314.96   …  -12268.3   -21796.1     -15126.5
  11954.6         563.014   14834.8       -29910.4   -27653.0     -31693.2
  -2737.38      13651.1    -15015.3       -36569.5    -1213.31     37991.8
 -18509.9      -19835.0     -1220.94      -14507.2    12079.3      -6357.57
   9406.07      16212.0     16813.8         8395.41  -25885.5      -8296.17
     -8.18472  -25102.0      9842.23   …   25218.8   -30858.7     -10630.2
    589.425     11314.9     19639.8         6047.98  -27205.4     -29201.4
 -19025.8        6569.77   -16634.5       -31733.5   -16747.7       7815.53
  -4475.6      -26359.9      1112.63       -3312.08   10004.9      12319.3
  -4516.24       1719.97   -17875.5       -13143.7   -20353.7        734.428
   2626.4       14470.8     13670.2    …  -12959.0      652.36     -6196.1
 -10047.0       -5147.07    -6015.51      -15256.2    -2941.89      9344.1
  -2517.26       -496.072  -15007.2         5077.28   -5347.57    -15647

In [85]:
𝕄₁*𝕄₂

29×26 Matrix{Float64}:
  -7217.73        761.369   -7314.96   …  -12268.3   -21796.1     -15126.5
  11954.6         563.014   14834.8       -29910.4   -27653.0     -31693.2
  -2737.38      13651.1    -15015.3       -36569.5    -1213.31     37991.8
 -18509.9      -19835.0     -1220.94      -14507.2    12079.3      -6357.57
   9406.07      16212.0     16813.8         8395.41  -25885.5      -8296.17
     -8.18472  -25102.0      9842.23   …   25218.8   -30858.7     -10630.2
    589.425     11314.9     19639.8         6047.98  -27205.4     -29201.4
 -19025.8        6569.77   -16634.5       -31733.5   -16747.7       7815.53
  -4475.6      -26359.9      1112.63       -3312.08   10004.9      12319.3
  -4516.24       1719.97   -17875.5       -13143.7   -20353.7        734.428
   2626.4       14470.8     13670.2    …  -12959.0      652.36     -6196.1
 -10047.0       -5147.07    -6015.51      -15256.2    -2941.89      9344.1
  -2517.26       -496.072  -15007.2         5077.28   -5347.57    -15647

In [89]:
@polyvar x y z

(x, y, z)

In [90]:
p = 2x + 3.0x^2*y^2 - y*z^4

-yz⁴ + 3.0x²y² + 2.0x

In [91]:
p(x=>3, y=>-4, z=>.05)

438.000025

In [92]:
differentiate(p, x)

6.0xy² + 2.0

In [93]:

variables(p)



(x, y, z)

In [94]:
p.terms


3-element Vector{Term{Float64, Monomial{(x, y, z), 3}}}:
 -yz⁴
 3.0x²y²
 2.0x

In [95]:
p.terms[1].coefficient


-1.0

In [96]:
p.terms[1].monomial


yz⁴

In [97]:

p.terms[1].monomial.exponents

(0, 1, 4)

In [98]:
NUM_TESTS = 20
DEGREE_DISTR = Categorical([.4, .2, .05, .05, .05, .05, .05, .05, .05, .05])
COEF_DISTR = Normal(0,10)
ALL_VARIABLES = @polyvar x₀ x₁ x₂ x₃ x₄ x₅ x₆ x₇ x₈ x₉

(x₀, x₁, x₂, x₃, x₄, x₅, x₆, x₇, x₈, x₉)

In [106]:
function random_point(polynomial, point_distr=COEF_DISTR)
    round.(rand(point_distr, length(variables(polynomial))), digits=2)
end
function random_polynomial(degree_distr=DEGREE_DISTR, nvars_distr=DEGREE_DISTR, nterms_distr=DEGREE_DISTR, coef_distr=COEF_DISTR)
    num_vars = rand(nvars_distr)
    num_terms = rand(nterms_distr)
    variables = ALL_VARIABLES[1:num_vars]
    polynomial = 0 * prod(variables)
    for term in 1:num_terms
        coef = round.(rand(coef_distr), digits=2)
        exponents = rand(degree_distr, num_vars) .- 1
        polynomial += coef * prod(variables .^ exponents)
    end
    return polynomial
end
function test_eval(polynomial, point)
    polynomial([var=>val for (var,val) in zip(variables(polynomial), point)]...)
end


test_eval (generic function with 1 method)

In [107]:
poly = random_polynomial()
point = random_point(poly)

7-element Vector{Float64}:
 16.37
 -2.07
  2.06
 -5.63
 13.89
 14.25
 -6.22

In [108]:
println(point)

[16.37, -2.07, 2.06, -5.63, 13.89, 14.25, -6.22]


In [112]:
poly

0.76x₂⁷x₄⁸x₆⁸ - 10.5x₂⁷x₃x₄²x₅⁷x₆ + 6.85x₂x₄⁵x₅⁷x₆ - 5.33x₁x₂x₃x₅⁵x₆ - 4.28x₄ - 6.92

In [115]:
0.76*(-2.07)^7*(-5.63)^8*(14.25)^8#

-2.1241837592045853e17

In [116]:
-10.5*(-2.07)^7*(2.06)*(-5.63)^2*(13.89)^7*14.25

1.587070838637811e14

In [117]:
6.85*(-2.07)*(-5.63)^5*(14.25)^7*(14.25)

1.363709311686849e14

In [118]:
-5.33*(16.37)*(-2.07)*(2.06)*(13.89)^5*(14.25)

2.741192578237207e9

In [119]:
-4.28*(-5.63)-6.92

17.1764

In [113]:
test_eval(poly, point)

3.646386377947649e17

In [215]:
poly = 4x₁^2*x₂ + x₂ + 4

4x₁²x₂ + x₂ + 4

In [216]:
point = [1, 2]

2-element Vector{Int64}:
 1
 2

In [233]:
test_eval(poly, point)

14

In [226]:
4*1^2*2

8

In [218]:
poly.terms

3-element Vector{Term{Int64, Monomial{(x₁, x₂), 2}}}:
 4x₁²x₂
 x₂
 4

In [299]:
poly

┌ Error: Failed to revise /home/DAVIDSON/komateer/Workspace/CSC381/dl_f22_project-0-KostasMateerStudent/gradients.jl
│   exception = (LoadError("/home/DAVIDSON/komateer/Workspace/CSC381/dl_f22_project-0-KostasMateerStudent/gradients.jl", 39, "unexpected \"end\""), Union{Ptr{Nothing}, Base.InterpreterIP}[Ptr{Nothing} @0x0000151024d659b0])
└ @ Revise /home/DAVIDSON/komateer/.julia/packages/Revise/VskYC/src/packagedef.jl:710
┌ Warning: The running code does not match the saved version for the following files:
│ 
│   /home/DAVIDSON/komateer/Workspace/CSC381/dl_f22_project-0-KostasMateerStudent/gradients.jl
│ 
│ If the error was due to evaluation order, it can sometimes be resolved by calling `Revise.retry()`.
│ Use Revise.errors() to report errors again. Only the first error in each file is shown.
│ Your prompt color may be yellow until the errors are resolved.
└ @ Revise /home/DAVIDSON/komateer/.julia/packages/Revise/VskYC/src/packagedef.jl:818


-8.98x₀x₁⁴x₂x₃²

-8.98x₀x₁⁴x₂x₃²

In [304]:
x\_0<tab> has poly.terms[1]

LoadError: syntax: extra token "poly" after end of expression

In [221]:
x.monomial.exponents

(2, 1)

In [222]:
poly.terms[2].monomial.exponents

(0, 1)

In [223]:
length(poly.terms[1].monomial.exponents)

2

In [203]:
poly.terms[1].monomial.exponents

(2, 0)

In [243]:
poly.terms[1].coefficient * point[1]^(poly.terms[1].monomial.exponents[1]) * point[2]^(poly.terms[2].monomial.exponents[2]) 
+ poly.terms[2].coefficient * point[1]^(poly.terms[1].monomial.exponents[1]) * point[2]^(poly.terms[2].monomial.exponents[2]) 
+ poly.terms[3].coefficient * point[1]^(poly.terms[1].monomial.exponents[1])

4

In [189]:
using TypedPolynomials

In [190]:
collect(Polynomials.monomials(p))

LoadError: UndefVarError: Polynomials not defined

In [267]:
evaluate(poly, point)

14

In [268]:
test_eval(poly, point)

14

In [269]:
poly.terms[3].monomial.exponents[1]

0

In [272]:
using Distributions
NUM_TESTS = 20
DEGREE_DISTR = Categorical([.4, .2, .05, .05, .05, .05, .05, .05, .05, .05])
COEF_DISTR = Normal(0,10)
ALL_VARIABLES = @polyvar x₀ x₁ x₂ x₃ x₄ x₅ x₆ x₇ x₈ x₉

(x₀, x₁, x₂, x₃, x₄, x₅, x₆, x₇, x₈, x₉)

In [277]:
using Distributions



NUM_TESTS = 20
DEGREE_DISTR = Categorical([.4, .2, .05, .05, .05, .05, .05, .05, .05, .05])
COEF_DISTR = Normal(0,10)
ALL_VARIABLES = @polyvar x₀ x₁ x₂ x₃ x₄ x₅ x₆ x₇ x₈ x₉

function test_eval(polynomial, point)
    polynomial([var=>val for (var,val) in zip(variables(polynomial), point)]...)
end

function random_polynomial(degree_distr=DEGREE_DISTR, nvars_distr=DEGREE_DISTR, nterms_distr=DEGREE_DISTR, coef_distr=COEF_DISTR)
    num_vars = rand(nvars_distr)
    num_terms = rand(nterms_distr)
    variables = ALL_VARIABLES[1:num_vars]
    polynomial = 0 * prod(variables)
    for term in 1:num_terms
        coef = round.(rand(coef_distr), digits=2)
        exponents = rand(degree_distr, num_vars) .- 1
        polynomial += coef * prod(variables .^ exponents)
    end
    return polynomial
end

function random_point(polynomial, point_distr=COEF_DISTR)
    round.(rand(point_distr, length(variables(polynomial))), digits=2)
end

random_point (generic function with 2 methods)

In [289]:
poly = random_polynomial()

-8.98x₀x₁⁴x₂x₃²

In [297]:
point

5-element Vector{Float64}:
  19.15
   9.49
 -11.26
  -9.93
 -12.09

In [296]:
point[1],(poly.terms[1].monomial.exponents[1])

(19.15, 1)

In [298]:
evaluate(poly, point)

1.5486270904185028e9

In [292]:
test_eval(poly, point)

1.5486270904185026e9

In [551]:
poly = random_polynomial()

-0.55x₀⁶x₂⁷x₃⁹ - 4.33x₀⁶x₁x₃²x₄⁸x₅ - 2.88x₂⁴x₃⁹x₄x₅ + 9.16x₀⁹x₁x₄⁴ + 1.05x₀⁶x₂x₃³x₄ - 10.08x₃x₄⁵x₅⁵

In [552]:
point = random_point(poly)

6-element Vector{Float64}:
   6.7
  10.31
  -9.79
  -1.66
 -10.56
  -9.64

In [553]:
vectory(poly, variables(poly)[1])

-3.3000000000000003x₀⁵x₂⁷x₃⁹ - 25.98x₀⁵x₁x₃²x₄⁸x₅ + 82.44x₀⁸x₁x₄⁴ + 6.300000000000001x₀⁵x₂x₃³x₄

In [554]:
differentiate(poly, variables(poly)[1])

-3.3000000000000003x₀⁵x₂⁷x₃⁹ - 25.98x₀⁵x₁x₃²x₄⁸x₅ + 82.44x₀⁸x₁x₄⁴ + 6.300000000000001x₀⁵x₂x₃³x₄

In [464]:
variables(poly)[1]+variables(poly)[2]

x₀ + x₁

In [435]:
x = (234, 333, 23)

(234, 333, 23)

In [429]:
getindex(x, 1)

1

In [431]:
find

x₀

In [387]:
poly.terms[1].monomial.exponents[1] = 1

LoadError: MethodError: no method matching setindex!(::NTuple{7, Int64}, ::Int64, ::Int64)

In [343]:
y = variables(poly)[1]

x₀

In [344]:
findall(x->x==y, variables(poly))

1-element Vector{Int64}:
 1

In [345]:
poly.terms

7-element Vector{Term{Float64, Monomial{(x₀, x₁, x₂, x₃, x₄, x₅, x₆), 7}}}:
 10.01x₀⁴x₃⁹x₅⁷
 14.74x₀⁵x₄⁷x₅⁷
 15.41x₀⁹x₂²x₃⁶x₅
 -12.41x₁x₂x₃⁷x₄⁶x₆²
 13.24x₀x₃⁶x₅⁶
 5.95x₀x₁x₂x₃³x₄x₅x₆²
 -1.74x₁x₂x₄

In [382]:
poly.terms[1].coefficient = 11

LoadError: setfield!: immutable struct of type Term cannot be changed

In [393]:
poly = x^1 + 3

x₀ + 3

In [396]:
poly + y^6

x₀⁶ + x₀ + 3

In [399]:
@polyvar q r s z

(q, r, s, z)

In [400]:
poly = q^2 + r + s^7

s⁷ + q² + r

In [401]:
poly + z^34

z³⁴ + s⁷ + q² + r

In [402]:
variables(poly)

(q, r, s)

In [403]:
@polyvar variables(poly)

LoadError: LoadError: Unsupported syntax. Expected x[a:b] for literal integers a and b
in expression starting at In[403]:1

In [557]:
poly = random_polynomial()
        

8.07x₀⁶x₁⁸x₄⁷x₆⁵x₇x₈x₉

In [558]:
point = random_point(poly)

10-element Vector{Float64}:
  -8.03
 -16.93
 -24.33
   2.1
 -14.1
   9.44
  -2.12
  15.66
 -18.65
  -2.57

In [566]:
symbolic_gradient(poly)


LoadError: UndefVarError: new_exponent not defined

In [560]:
differentiate(poly, variables(poly))

10-element Vector{Polynomial{Float64, Term{Float64, Monomial{(x₀, x₁, x₂, x₃, x₄, x₅, x₆, x₇, x₈, x₉), 10}}, Vector{Term{Float64, Monomial{(x₀, x₁, x₂, x₃, x₄, x₅, x₆, x₇, x₈, x₉), 10}}}}}:
 48.42x₀⁵x₁⁸x₄⁷x₆⁵x₇x₈x₉
 64.56x₀⁶x₁⁷x₄⁷x₆⁵x₇x₈x₉
 0.0
 0.0
 56.49x₀⁶x₁⁸x₄⁶x₆⁵x₇x₈x₉
 0.0
 40.35x₀⁶x₁⁸x₄⁷x₆⁴x₇x₈x₉
 8.07x₀⁶x₁⁸x₄⁷x₆⁵x₈x₉
 8.07x₀⁶x₁⁸x₄⁷x₆⁵x₇x₉
 8.07x₀⁶x₁⁸x₄⁷x₆⁵x₇x₈